In [13]:
demo=[23,32,1,14]
demo

[23, 32, 1, 14]

In [14]:
!pip install numpy

In [15]:
import numpy as np

In [16]:
demo=np.array([312,432,343,21])
demo

array([312, 432, 343,  21])

In [17]:
w1=2
w2=3
w3=1
w4=0

In [18]:
weights=[w1,w2,w3,w4]
weights


[2, 3, 1, 0]

type(weights)

In [19]:
weights=np.array([w1,w2,w3,w4])
weights

array([2, 3, 1, 0])

In [20]:
type(demo)
# type(weights)

numpy.ndarray

# operating on numpy array

In [21]:
help(np.dot)

Help on _ArrayFunctionDispatcher in module numpy:

dot(...)
    dot(a, b, out=None)
    
    Dot product of two arrays. Specifically,
    
    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).
    
    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.
    
    - If either `a` or `b` is 0-D (scalar), it is equivalent to
      :func:`multiply` and using ``numpy.multiply(a, b)`` or ``a * b`` is
      preferred.
    
    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.
    
    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of
      `b`::
    
        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
    
    It uses an optimized BLAS library when possible (see `numpy.linalg`).
    
    Parameters
    -----

In [22]:
demo

array([312, 432, 343,  21])

In [23]:
weights

array([2, 3, 1, 0])

In [24]:
np.dot(demo,weights)

2263

In [25]:
(demo*weights).sum()

2263

In [26]:
# python lists
arr1=list(range(100000))
arr2=list(range(100000,200000))

# numpy array
arr1_np=np.array(arr1)
arr2_np=np.array(arr2)

In [27]:
%%time
result=0
for x1,x2 in zip(arr1,arr2):
    result+=x1*x2
result

CPU times: total: 31.2 ms
Wall time: 52.9 ms


833323333350000

## multi-dimensional numpy array

In [28]:
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58],
                         [102, 43, 37],
                         [69, 96, 70]])
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [29]:
# 3D array 
arr3 = np.array([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.5]]])

In [30]:
arr3.shape

(2, 2, 3)

In [31]:
arr3.type

AttributeError: 'numpy.ndarray' object has no attribute 'type'

In [ ]:
climate_data.dtype

In [ ]:
arr3

In [ ]:
climate_data

In [ ]:
weights2=[2,3,4]
weights=np.array(weights2)

In [ ]:
weights2

In [ ]:
np.matmul(climate_data,weights2)

In [ ]:
climate_data @ weights2

In [ ]:
import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

In [ ]:
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)

In [ ]:
climate_data

In [ ]:
climate_data.shape

In [ ]:
weights4=np.array([0.2,0.3,0.5,0.6])
weights4

In [ ]:
yeilds = climate_data @ weights
yeilds

In [ ]:
yeilds.shape

In [ ]:
climate_results=np.concatenate((climate_data,yeilds.reshape(10000,1)),axis=1)
climate_results

In [ ]:
np.savetxt('climate_result.txt',climate_results,fmt='%.2f',header='temperature,rainfall,humidity,yeilds_appels',comments='')

In [34]:
# array broadcasting
arr2 = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 1, 2, 3]])
arr2.shape

(3, 4)

In [35]:
arr4 = np.array([4, 5, 6, 7])
arr4.shape

(4,)

In [36]:
arr2 + arr4

array([[ 5,  7,  9, 11],
       [ 9, 11, 13, 15],
       [13,  6,  8, 10]])

In [37]:
# array comparision
arr1 = np.array([[1, 2, 3], [3, 4, 5]])
arr2 = np.array([[2, 2, 3], [1, 2, 5]])

arr1==arr2

array([[False,  True,  True],
       [False, False,  True]])

## array indexing and slicing

In [38]:
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])

In [40]:
arr3.shape

(3, 2, 4)

In [41]:
# single element
arr3[1,1,2]

36.0

In [43]:
# range
arr3[1: , 0:1, :2

array([[[15. , 16. , 17. , 21. ],
        [63. , 92. , 36. , 18. ]],

       [[98. , 32. , 81. , 23. ],
        [17. , 18. , 19.5, 43. ]]])